import { chmod, mkdir, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { chromium, type Browser } from 'playwright-core';
import type { ExecutorConfig } from '../config.js';

const BASE_MOUNTS = ['/usr', '/lib', '/lib64', '/bin', '/etc/ld.so.cache', '/etc/fonts', '/usr/share/fonts', '/dev/null', '/dev/zero', '/dev/urandom', '/dev/random'];
const q = (s: string) => `'${s.replace(/'/g, `'\\''`)}'`;

/**
 * Playwright launches Chromium through this wrapper, which execs it inside nsjail: no network
 * interfaces (not even loopback), uid 65534, read-only system, tmpfs profile, cgroup limits and
 * the same seccomp policy as every other jail. Playwright talks to it over the inherited pipe
 * file descriptors 3/4 (--remote-debugging-pipe), so no port is opened anywhere.
 */
export async function writeChromeWrapper(cfg: ExecutorConfig): Promise<string> {
  const path = join(cfg.workRoot, 'bin', 'chrome-jail.sh');
  await mkdir(dirname(path), { recursive: true });
  const chromeDir = dirname(dirname(cfg.chromiumPath));
  const nsjail = [
    cfg.nsjailPath, '-Mo', '--quiet', '--hostname', 'jail',
    '-u', '65534:65534:1', '-g', '65534:65534:1',
    '--time_limit', '120', '--rlimit_as', 'inf', '--rlimit_stack', '256', '--rlimit_nofile', '1024', '--rlimit_fsize', '64', '--rlimit_core', '0',
    '--cgroup_mem_max', String(1024 * 1024 * 1024), '--cgroup_pids_max', '256', '--cgroup_cpu_ms_per_sec', '2000',
    '--iface_no_lo', '--seccomp_policy', cfg.seccompPolicy,
    ...(cfg.cgroupV2 ? ['--use_cgroupv2', '--cgroupv2_mount', cfg.cgroupRoot, '--cgroup_mem_swap_max', '0'] : []),
    ...BASE_MOUNTS.flatMap((m) => ['-R', m]),
    '-R', chromeDir,
    '-m', `none:/tmp:tmpfs:size=${256 * 1024 * 1024}`, '-m', `none:/dev/shm:tmpfs:size=${128 * 1024 * 1024}`,
    '--env', 'HOME=/tmp', '--env', 'LANG=C.UTF-8',
    '--pass_fd', '3', '--pass_fd', '4',
    '--', cfg.chromiumPath,
    // Chromium's own sandbox needs namespaces our seccomp policy forbids; nsjail is the sandbox.
    '--no-sandbox', '--no-zygote', '--disable-dev-shm-usage', '--disable-gpu',
    '--disable-background-networking', '--disable-component-update', '--disable-domain-reliability', '--no-pings',
    '--host-resolver-rules=MAP * ~NOTFOUND', '--proxy-server=http://0.0.0.0:9', '--force-webrtc-ip-handling-policy=disable_non_proxied_udp',
  ];
  // Fixed arguments are single-quoted; Playwright's arguments pass through a bash array untouched.
  const script = `#!/bin/bash
# Generated by the executor. Rewrites Playwright's host profile dir to the jail's tmpfs.
args=()
for a in "$@"; do
  case "$a" in
    --user-data-dir=*) args+=("--user-data-dir=/tmp/profile") ;;
    *) args+=("$a") ;;
  esac
done
exec ${nsjail.map(q).join(' ')} "\${args[@]}"
`;
  await writeFile(path, script, { mode: 0o755 });
  await chmod(path, 0o755);
  return path;
}

export async function launchJailedChromium(wrapper: string): Promise<Browser> {
  return chromium.launch({ executablePath: wrapper, timeout: 30_000, handleSIGINT: false, handleSIGTERM: false, handleSIGHUP: false });
}
